### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/podcast-transcripts#96]
This repo doesn't have `CONTRIBUTING.md` file.
We might need  to create the file as the guide for people to contribute to our repo.
We can adapt the [CONTRIBUTING.md from virtualcoffee.io repo](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/CONTRIBUTING.md) to create one.

**Comment by danieltott** [comment]
As long as the contributing guide highlights the [Transcriptions-Guidelines](https://github.com/Virtual-Coffee/podcast-transcripts/blob/main/Transcriptions-Guidelines.md) this sounds good.
