### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/podcast-transcripts#97]
This repo doesn't have `CODE_OF_CONDUCT.md` file and we must create one.
We can use the same content as in [virtualcoffee.io repo](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/CODE_OF_CONDUCT.md).

**Comment by adiati98** [comment]
Noted and thanks, @danieltott!
I'll make a PR for #96 and #98 soon😀

**Comment by danieltott** [comment]
Thanks @adiati98 - be sure to do them in separate PRs so we can work them out individually ❤️
