### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by adiati98** [Virtual-Coffee/podcast-transcripts#98]
As this repo is an open source, we need a license for this repo.

I have been looking around for transcriptions-related linceses, and found that [se-unlocked podcast](https://github.com/mgreiler/se-unlocked) is using [Creative Commons Attribution Share Alike 4.0 International](https://choosealicense.com/licenses/cc-by-sa-4.0/) as their license for their transcripts repo.

So, we might as well using this license for our podcast-transcripts repo.

**Comment by danieltott** [comment]
I'm not so sure about this one - I'll have to look in to it more. Repositories with no license by default give people no permissions to use the contents, which I would much prefer over a license that gives more permissions then we actually want. This repo is 99% content which is copyrighted by VirtualCoffeeIO.

**Comment by adiati98** [comment]
Gotcha! If that's the case, then we don't need license at all 👍🏼
